### PR TITLE
Raylib 4.0

### PR DESCRIPTION
**Pull request by Rover656**
This is marked as draft as I've not quite finished going over everything. This is simply a "change things till it builds" kind of deal.

The only major thing really ready for review right now is the raylib-sys build script. Binding generation is now done in there on the fly as opposed to by a developer manually. This should hopefully take a bit of the manual work out of maintenance of the library in future. This also adds a quick if check for web to stop a panic for no reason.

Also changes cmake build system to ninja, this helps developers using the mingw toolchain as visual studio isn't present on the path for these users (like myself). VS still includes ninja so it shouldn't be any hassle.

### CODE REVIEW

**Comment by Dacode45** [comment]
I like everything about this except the on-the-fly binding generation. There's a lot of cross-compatibility that usually needs to be manually added. 

Like the dynamic windows bindings use a 32-bit integer as bools which leads to subtle errors down the line. We'll see how it goes though. I'll create a 4.0 branch and you can merge your pr in there.

**Comment by Rover656** [comment]
> I like everything about this except the on-the-fly binding generation. There's a lot of cross-compatibility that usually needs to be manually added.
> 
> Like the dynamic windows bindings use a 32-bit integer as bools which leads to subtle errors down the line. We'll see how it goes though. I'll create a 4.0 branch and you can merge your pr in there.

I believe most edge-cases have been fixed; for example using 32-bit ints for bools is fixed (by an odd workaround, but it works nonetheless)
I'll try and run extensive tests on as many archs as I am able to make sure we're all god

**Comment by Rover656** [comment]
Going to get rust nightly installed and check/write tests tonight, then this should be ready for some extensive testing

**Comment by Rover656** [comment]
Okay, should be go for a review :)

**Pull request merged**
