### PR TITLE
`raylib-sys` crate for raw bindings

### PR DESCRIPTION
**Pull request by dtcristo**
Regarding #1, I've done some work to build a `raylib-sys` crate, ported from [dtcristo/raylib-rust](https://github.com/dtcristo/raylib-rust/). It will build on Windows, Mac and Linux and will automatically download the raylib static library and link to it. The bindings are generated automatically and put in `bindings.rs` within the build directory (you should view this).

The following tools are required to build `raylib-sys`:
- `curl`
- `clang` - Windows binaries can be downloaded [here](https://releases.llvm.org/download.html)
- `pkg-config` - Only required for macOS and Linux

You can attempt to run the example with the following:
```sh
cargo run --package raylib-sys --example raylib_rust_logo
```

I've also moved some files around creating two sub crates. The main crate (renamed to just `raylib`) and the `raylib-sys` crates live side-by-side.

Hopefully you could use this crate to replace your `raylib.rs` bindings file. But will take some more work, any maybe require configuration changes in the `bindgen` config within `build.rs`. I have not done any work integrating the main crate yet, so maybe don't merge into `master` as is.

### CODE REVIEW

**Comment by dtcristo** [comment]
I've made some additional changes that allow the original FFI bindings to still function, while depending on `raylib-sys` to handle downloading raylib and linker configuration. This should work with Windows, macOS and Linux automatically.

If you checkout this branch, you can test the build script and linker configuration by running the following example.
```sh
cargo run --package raylib --example hello_world
```

@deltaphc, if you're happy to eventually go down this path of having automatically generated bindings, I think this PR should be ready to merge now. Updating the main library to use the new FFI layer will take time, specifically around the structs and enums. They are automatically defined by bindgen so if we wanted to add `impl`s to them, it might be hard. I don't know how to solve this, other than redefine new structs in the `raylib` crate and use `std::mem::transmute` or manual conversion (adding overhead).

This fixes #5, as linker arguments are handled within the build script for all three platforms. @davelpz, you can test out this change with the following update to your `Cargo.toml`. Note `raylib-rs` renamed to just `raylib`, so update your program accordingly. There are also some additional dependencies needed by the new `raylib-sys` crate, see the updates I made to the readme.

```toml
[dependencies]
raylib = { git = "https://github.com/dtcristo/raylib-rs", branch = "feature/raylib-sys" }
```

**Comment by deltaphc** [comment]
Upon further thought, I think what I'll do is that instead of merging this big change all at once, I will use it as a reference for incrementally adding onto `master`, if that's okay with you. I don't want to sound too demanding on the things I want, and at the same time I know there's a lot of good material in this PR, so I think pulling bits and pieces at a time will be the more sensible approach for me.

**Comment by dtcristo** [comment]
No worries. Use it however you want.

Regarding the dependency on `clang`, it is a dependency of bindgen. It needs this for parsing the `raylib.h` header file to build the bindings. Because `raylib-sys` generates the bindings at build time, this dependency will always be required (if you use this approach). When "vendoring" the bindings into the crate (as is currently the case with the `raylib.rs` file) you have the advantage of not needing `clang`, but it means if you update to a new version of raylib, you won't get any compile errors (perhaps linker errors). The bindings will be out of date and you might not know until you run the application. I guess this would work if you manually run bindgen on each new version of raylib and update `bindings.rs`. That could work, but you want to not make any changes to the output of bindgen for easy upgrading. Have a read of the [bindgen book](https://rust-lang.github.io/rust-bindgen/introduction.html) for more info. It's a good resource.

Regarding support for `x86_64-pc-windows-gnu`. It might just work if you un-comment [these lines](https://github.com/dtcristo/raylib-rs/blob/f9f965f224dad7061ad700d295733eccd2b30eb0/raylib-sys/build.rs#L97-L99), but I haven't been able to test this.

Regarding `curl` and `tar`, compatible binaries seemed to come with Windows 10, but not sure. You can probably do a platform check within the build script to replace the need for these.

**Comment by deltaphc** [comment]
Since the main raylib/raylib-sys split has been done, I'm going to close this PR. I'll continue to reference it for when I get around to adding automagic download/bindgen functionality.

**Pull request closed without merging**
